#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <egg-uri> <prefix>" >&2
	exit 1
}
[ -n "$1" ] && [ -n "$2" ] || usage

EGG=$1
PREFIX=$2

mkdir /tmp/setuptoolsinstall-$$
cd /tmp/setuptoolsinstall-$$
wget $EGG
PATH="$PREFIX/bin:$PATH" sh * --prefix=$PREFIX
cd /tmp
rm -rf /tmp/setuptoolsinstall-$$
